version: '3.8'
services:
  mongodb:
      image: mongo:latest
      container_name: dkrcomp-mongodb-container
      restart: unless-stopped
      ports:
          - '27017:27017'
      environment:
          - MONGO_INITDB_ROOT_USERNAME=tenisu_user
          - MONGO_INITDB_ROOT_PASSWORD=tenisu_password
          - MONGO_INITDB_DATABASE=tenisu_db
      volumes:
          - mongo_data:/data/db

volumes:
  mongo_data: